### PR TITLE
[TASK] TYPO3 v10

### PR DESCRIPTION
**Pull request by achimfritz**
first part of run EXT:theme with TYPO3 v10. This only fix some general stuff, (the BE-Module works). But there are there a still more tasks todo ...

### CODE REVIEW

**Comment by fazzyx** [comment]
I have a running version under 10. Still under review, but it looks good. 
Should I make them available to you?

**Comment by achimfritz** [comment]
Hi @fazzyx , why not make a PR into this repo?

**Comment by kaystrobach** [comment]
Just found the dependency to gridelements - this is not mandatory. Just needed, if we rely on https://github.com/typo3-themes/themes_gridelements/blob/master/composer.json where the dependency is missing.

**Comment by kaystrobach** [comment]
see #217

**Comment by fazzyx** [comment]
> Hi @fazzyx , why not make a PR into this repo?

Ok, we will do this.

**Comment by Wipster** [comment]
Here is the PR with the code @fazzyx was talking about. Has some style ci issues I'm going to look into.

https://github.com/typo3-themes/themes/pull/218

**Pull request merged**
