### PR TITLE
Typo3 8 compatibility

### PR DESCRIPTION
**Pull request by anjeylink**
fixes for typo3 8.x

### CODE REVIEW

**Comment by kaystrobach** [comment]
@anjeylink could you please fix the 2 remaining style ci problems?

In the meantime will will do the review - thank you for your big PR!

**Comment by anjeylink** [comment]
@kaystrobach i did some fixes, but i'm not very experienced with unit tests, can you check it ?

**Comment by MattiasNilsson** [comment]
@kaystrobach @anjeylink Could you guys take a look at this PR?

**Comment by kaystrobach** [comment]
@anjeylink @MattiasNilsson will check next week, anyway there will be a dedicated version for v8, I will do only minimal backports 😏

**Comment by kaystrobach** [comment]
will check it out next week - feel free to ping my again if i miss it

**Comment by tdeuling** [comment]
Thanks for all your work and your pull requests :) You did a great job!
Today we've merged them into our [8-0](https://github.com/typo3-themes/themes/tree/8-0) branch - therefore we close the pull request.

**Pull request closed without merging**
