### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by cristianbuja**
Related to issue #142

### CODE REVIEW

**Comment by cristianbuja** [comment]
Hops, there is an error...

**Comment by kaystrobach** [comment]
leave it open please, maybe a problem in the ci system ;)

**Comment by cristianbuja** [comment]
How can I correct an error in my commit?

**Comment by cristianbuja** [comment]
Ok I think I find how

**Comment by kaystrobach** [comment]
i think this one found it's way to master already

**Pull request closed without merging**
