### PR TITLE
[TASK] make templates without root-flag themeable

### PR DESCRIPTION
**Pull request by achimfritz**

### CODE REVIEW

**Comment by achimfritz** [comment]
are there any reasons for requiring root-flag set on sys_templates? I do not see.

**Comment by kaystrobach** [comment]
Reason is to avoid user confusion and dependent themes.

The history has shown massive problems with mixed themes on a single page.

**Comment by achimfritz** [comment]
Hi @kaystrobach, thanks for Feedback. Can we introduce an Extension-Konfiguration-Parameter, to allow "non-root-flagged" sys_templates as theme? Our Customer use this extension as an "advanced TS-Constants Editor" for "Page-Configuration" (with just one theme). In that case it is disturbing to have set the root-flag on each sys_template, which destroys inheritance.

**Comment by kaystrobach** [comment]
I would prefer a site config setting instead of an extension config. Then this can be set per tree. Makes more sense imho. Default should be off 😅

**Comment by achimfritz** [comment]
@kaystrobach i have pushed new commits

**Comment by kaystrobach** [comment]
Do you think it makes sense to add a tca modification to the site config? Imho this makes usage way easier for the user

**Comment by achimfritz** [comment]
Hi @kaystrobach do you think we need a TCA Modification for site config? if you prefer, i can do?

**Comment by kaystrobach** [comment]
I’m unsure right now. Give some more days to think about it please

**Comment by kaystrobach** [comment]
i merge that for now - maybe this needs to be transfered to a site config lateron

**Pull request merged**
